#!/usr/bin/env python3
"""
Quick setup script for .env configuration
"""

import os
from pathlib import Path


def setup_env():
    print("=" * 60)
    print("NovaAvatar Environment Setup")
    print("=" * 60)
    print()

    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        response = input(".env file already exists. Overwrite? (y/n): ")
        if response.lower() != 'y':
            print("Setup cancelled.")
            return

    print("Let's set up your API keys...")
    print()

    # Get API keys
    print("1. OpenAI API Key (required for GPT-4 script generation)")
    print("   Get from: https://platform.openai.com/api-keys")
    openai_key = input("   Enter your OpenAI API key: ").strip()

    print()
    print("2. Replicate API Token (required for Flux image generation)")
    print("   Get from: https://replicate.com/account/api-tokens")
    replicate_token = input("   Enter your Replicate token: ").strip()

    print()
    print("3. Model Selection")
    use_14b = input("   Use 14B model? (needs 21-36GB VRAM) [y/N]: ").strip().lower() == 'y'

    print()
    print("4. Optional: Reddit API (for content scraping)")
    use_reddit = input("   Configure Reddit API? [y/N]: ").strip().lower() == 'y'

    reddit_id = ""
    reddit_secret = ""
    if use_reddit:
        reddit_id = input("   Reddit Client ID: ").strip()
        reddit_secret = input("   Reddit Client Secret: ").strip()

    print()
    print("5. Optional: NewsAPI (for content scraping)")
    use_newsapi = input("   Configure NewsAPI? [y/N]: ").strip().lower() == 'y'

    newsapi_key = ""
    if use_newsapi:
        newsapi_key = input("   NewsAPI Key: ").strip()

    # Create .env file
    env_content = f"""# NovaAvatar Configuration
# Generated by setup_env.py

# =============================================================================
# AI Services (REQUIRED)
# =============================================================================
OPENAI_API_KEY={openai_key}
REPLICATE_API_TOKEN={replicate_token}

# =============================================================================
# Model Configuration
# =============================================================================
USE_14B_MODEL={'true' if use_14b else 'false'}

# =============================================================================
# Content Sources (Optional)
# =============================================================================
"""

    if reddit_id and reddit_secret:
        env_content += f"""REDDIT_CLIENT_ID={reddit_id}
REDDIT_CLIENT_SECRET={reddit_secret}
"""
    else:
        env_content += """# REDDIT_CLIENT_ID=your_client_id
# REDDIT_CLIENT_SECRET=your_client_secret
"""

    if newsapi_key:
        env_content += f"""NEWSAPI_KEY={newsapi_key}
"""
    else:
        env_content += """# NEWSAPI_KEY=your_newsapi_key
"""

    env_content += """
# =============================================================================
# Generation Parameters (Optimized defaults)
# =============================================================================
NUM_STEPS=25
GUIDANCE_SCALE=4.5
TEA_CACHE_THRESH=0.14
ENABLE_VRAM_MANAGEMENT=true

# =============================================================================
# Server Configuration
# =============================================================================
GRADIO_SERVER_PORT=7860
API_SERVER_PORT=8000
AUTO_APPROVE=false
"""

    # Write file
    with open(".env", "w") as f:
        f.write(env_content)

    print()
    print("=" * 60)
    print("✅ .env file created successfully!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Verify models are downloaded:")
    print("   ls pretrained_models/")
    print()
    print("2. Run setup check:")
    print("   python run.py setup")
    print()
    print("3. Launch NovaAvatar:")
    print("   python run.py")
    print()
    print("   Then visit: http://localhost:7860")
    print()


if __name__ == "__main__":
    setup_env()
